spring.application.name=${SPRING_APPLICATION_NAME}
spring.config.import=optional:file:.env[.properties]

server.port=${SERVER_PORT}
server.forward-headers-strategy=${SERVER_FORWARD_HEADERS_STRATEGY}

# MySQL
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME}

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL}
spring.jpa.properties.hibernate.dialect=${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT}

# Eureka
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
eureka.instance.prefer-ip-address=${EUREKA_INSTANCE_PREFER_IP_ADDRESS}

# JWT (same secret as all other services)
jwt.secret=${JWT_SECRET}

# RabbitMQ
spring.rabbitmq.host=${SPRING_RABBITMQ_HOST}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD}
spring.rabbitmq.listener.simple.missing-queues-fatal=${SPRING_RABBITMQ_LISTENER_SIMPLE_MISSING_QUEUES_FATAL}
spring.rabbitmq.listener.simple.retry.enabled=${SPRING_RABBITMQ_LISTENER_SIMPLE_RETRY_ENABLED}
spring.rabbitmq.listener.simple.retry.initial-interval=${SPRING_RABBITMQ_LISTENER_SIMPLE_RETRY_INITIAL_INTERVAL}
spring.rabbitmq.listener.simple.retry.max-attempts=${SPRING_RABBITMQ_LISTENER_SIMPLE_RETRY_MAX_ATTEMPTS}

# Mail — USE Gmail App Password, NOT your real password
spring.mail.host=${SPRING_MAIL_HOST}
spring.mail.port=${SPRING_MAIL_PORT}
spring.mail.username=${STOCKPRO_MAIL_USERNAME}
spring.mail.password=${STOCKPRO_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=${SPRING_MAIL_SMTP_AUTH}
spring.mail.properties.mail.smtp.starttls.enable=${SPRING_MAIL_SMTP_STARTTLS_ENABLE}
spring.mail.properties.mail.smtp.starttls.required=${SPRING_MAIL_SMTP_STARTTLS_REQUIRED}
spring.mail.properties.mail.smtp.ssl.trust=${SPRING_MAIL_SMTP_SSL_TRUST}
spring.mail.properties.mail.smtp.connectiontimeout=${SPRING_MAIL_SMTP_CONNECTION_TIMEOUT}
spring.mail.properties.mail.smtp.timeout=${SPRING_MAIL_SMTP_TIMEOUT}
spring.mail.properties.mail.smtp.writetimeout=${SPRING_MAIL_SMTP_WRITE_TIMEOUT}

stockpro.alert.email-to=${STOCKPRO_ALERT_EMAIL_TO}
stockpro.frontend.dashboard-url=${STOCKPRO_FRONTEND_DASHBOARD_URL}

# Actuator
management.endpoints.web.exposure.include=${MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE}
management.endpoint.health.show-details=${MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS}
management.health.mail.enabled=${MANAGEMENT_HEALTH_MAIL_ENABLED}

# Swagger / OpenAPI
springdoc.api-docs.path=${SPRINGDOC_API_DOCS_PATH}
springdoc.swagger-ui.path=${SPRINGDOC_SWAGGER_UI_PATH}
springdoc.swagger-ui.enabled=${SPRINGDOC_SWAGGER_UI_ENABLED}
