spring.application.name=${SPRING_APPLICATION_NAME}
spring.config.import=optional:file:.env[.properties]
server.port=${SERVER_PORT}

#  MySQL
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME}

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL}
spring.jpa.properties.hibernate.format_sql=${SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL}

server.forward-headers-strategy=${SERVER_FORWARD_HEADERS_STRATEGY}
spring.jpa.properties.hibernate.dialect=${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT}

#  Eureka
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
eureka.instance.prefer-ip-address=${EUREKA_INSTANCE_PREFER_IP_ADDRESS}

#  JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

#  Logging
logging.level.org.springframework=${LOGGING_LEVEL_ORG_SPRINGFRAMEWORK}
logging.level.com.stockpro=${LOGGING_LEVEL_COM_STOCKPRO}

#  Actuator
management.endpoints.web.exposure.include=${MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE}
management.endpoint.health.show-details=${MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS}

stockpro.internal.service-token=${STOCKPRO_INTERNAL_SERVICE_TOKEN}

# ℹ Info
info.app.name=${INFO_APP_NAME}
info.app.version=${INFO_APP_VERSION}
info.app.description=${INFO_APP_DESCRIPTION}

stockpro.alert.low-stock-threshold=${STOCKPRO_ALERT_LOW_STOCK_THRESHOLD}

# RabbitMQ Config
spring.rabbitmq.host=${SPRING_RABBITMQ_HOST}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD}
