spring.application.name=${SPRING_APPLICATION_NAME}
spring.config.import=optional:file:.env[.properties]


server.port=${SERVER_PORT}
jwt.secret=${JWT_SECRET}

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}


spring.jpa.properties.hibernate.dialect=${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL}
server.forward-headers-strategy=${SERVER_FORWARD_HEADERS_STRATEGY}

# Eureka config
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
eureka.instance.prefer-ip-address=${EUREKA_INSTANCE_PREFER_IP_ADDRESS}


#=====================
# Actuator
#=====================
management.endpoints.web.exposure.include=${MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE}
management.endpoint.health.show-details=${MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS}

management.endpoint.shutdown.enabled=${MANAGEMENT_ENDPOINT_SHUTDOWN_ENABLED}
management.endpoints.web.base-path=${MANAGEMENT_ENDPOINTS_WEB_BASE_PATH}

#===============================
#Swagger / OpenAPI
#===============================
springdoc.api-docs.path=${SPRINGDOC_API_DOCS_PATH}
springdoc.swagger-ui.path=${SPRINGDOC_SWAGGER_UI_PATH}
springdoc.swagger-ui.enabled=${SPRINGDOC_SWAGGER_UI_ENABLED}

#===============================
# Redis Cache
#===============================
spring.cache.type=${SPRING_CACHE_TYPE}
spring.data.redis.host=${SPRING_DATA_REDIS_HOST}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT}
spring.data.redis.timeout=${SPRING_DATA_REDIS_TIMEOUT}
stockpro.cache.supplier-ttl-minutes=${STOCKPRO_CACHE_SUPPLIER_TTL_MINUTES}
