spring.application.name=${SPRING_APPLICATION_NAME}
spring.config.import=optional:file:.env[.properties]


jwt.secret=${JWT_SECRET}
server.port=${SERVER_PORT}

#  MySQL Config
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

#  JPA Config
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL}
spring.jpa.properties.hibernate.dialect=${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT}
server.forward-headers-strategy=${SERVER_FORWARD_HEADERS_STRATEGY}

#  Eureka
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}


#=====================
#Actuator
#======================
management.endpoints.web.exposure.include=${MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE}
management.endpoint.health.show-details=${MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS}

# Optional info
info.app.name=${INFO_APP_NAME}
info.app.version=${INFO_APP_VERSION}
info.app.description=${INFO_APP_DESCRIPTION}

#===============================
#Swagger / OpenAPI
#===============================
springdoc.api-docs.path=${SPRINGDOC_API_DOCS_PATH}
springdoc.swagger-ui.path=${SPRINGDOC_SWAGGER_UI_PATH}
springdoc.swagger-ui.enabled=${SPRINGDOC_SWAGGER_UI_ENABLED}

#===============================
# Redis Cache
#===============================
spring.cache.type=${SPRING_CACHE_TYPE}
spring.data.redis.host=${SPRING_DATA_REDIS_HOST}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT}
spring.data.redis.timeout=${SPRING_DATA_REDIS_TIMEOUT}
stockpro.cache.product-ttl-minutes=${STOCKPRO_CACHE_PRODUCT_TTL_MINUTES}
