spring.application.name=${SPRING_APPLICATION_NAME}
spring.config.import=optional:file:.env[.properties]
server.port=${SERVER_PORT}

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME}

spring.jpa.database-platform=${SPRING_JPA_DATABASE_PLATFORM}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL}

server.forward-headers-strategy=${SERVER_FORWARD_HEADERS_STRATEGY}

eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
eureka.instance.prefer-ip-address=${EUREKA_INSTANCE_PREFER_IP_ADDRESS}

jwt.secret=${JWT_SECRET}

management.endpoints.web.exposure.include=${MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE}
management.endpoint.health.show-details=${MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS}

stockpro.internal.service-token=${STOCKPRO_INTERNAL_SERVICE_TOKEN}
stockpro.warehouse-service.base-url=${WAREHOUSE_SERVICE_BASE_URL}

#===============================
#Swagger / OpenAPI
#===============================
springdoc.api-docs.path=${SPRINGDOC_API_DOCS_PATH}
springdoc.swagger-ui.path=${SPRINGDOC_SWAGGER_UI_PATH}
springdoc.swagger-ui.enabled=${SPRINGDOC_SWAGGER_UI_ENABLED}
